#ifndef __REGISTRATION_H
#define __REGISTRATION_H

typedef enum{
    REGISTRATION_STATUS_OK,
    REGISTRATION_STATUS_WRONG_EMAIL_DOMAIN,
    REGISTRATION_STATUS_ALREADY_REGISTERED,
    REGISTRATION_STATUS_TOO_MANY_REGISTRATIONS_TODAY
} REGISTRATION_STATUS;

REGISTRATION_STATUS registerUser(const char *email);

#endif //__REGISTRATION_H